/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   cuba-lookup.html
 */

/// <reference path="../polymer/types/polymer.d.ts" />
/// <reference path="../paper-button/paper-button.d.ts" />
/// <reference path="../paper-dialog/paper-dialog.d.ts" />
/// <reference path="../paper-dialog-scrollable/paper-dialog-scrollable.d.ts" />

/**
 * `cuba-lookup` component provides an ability to specify entity `-list` component
 * in order to select an entity instance for a reference attribute.
 * The list component should be marked passed into `lookup-screen` slot.
 *
 *
 *     <link rel="demo-manufacturers-by-country.html">
 *
 *     <cuba-lookup picked-entity="{{entity.manufacturer}}">
 *       <div slot="dropdown">
 *       ...
 *       </div>
 *       <demo-manufacturers-by-country slot="lookup-screen"></demo-manufacturers-by-country>
 *     </cuba-lookup>
 */
interface CubaLookupElement extends Polymer.Element {

  /**
   * Entity which has been picked by user.
   */
  pickedEntity: object|null|undefined;

  /**
   * Entity which is currently selected in lookup dialog.
   */
  selectedEntity: object|null|undefined;
  _lookupElement: object|null|undefined;
  ready(): void;
  showLookupScreen(): void;
  _select(): void;
  _cancel(): void;
}

interface HTMLElementTagNameMap {
  "cuba-lookup": CubaLookupElement;
}
