/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   cuba-ui.html
 */

/// <reference path="cuba-lookup.d.ts" />
/// <reference path="cuba-entity-list-view-behavior.d.ts" />
/// <reference path="cuba-entity-edit-view-behavior.d.ts" />

