/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   cuba-entity-edit-view-behavior.html
 */

interface CubaEntityEditViewBehavior {
  entityId: string|null|undefined;
  entity: object|null|undefined;
  _handleEntityIdChange(newValue: any): void;
  _save(): void;
  _onSuccess(): void;
  _onError(): void;
  _cancel(): void;
  _delete(): void;
  _isInvalid(err: any): any;
}

declare const CubaEntityEditViewBehavior: object;
