/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   cuba-progress-indicator.html
 */

/// <reference path="../polymer/types/polymer.d.ts" />

/**
 * `<cuba-progress-indicator>` is a Polymer 2 element for data loading progress indication.
 *
 * ```html
 * <cuba-progress-indicator></cuba-progress-indicator>
 * ```
 *
 * ### Styling
 *
 * `<cuba-progress-indicator>` provides the following custom properties and mixins
 * for styling:
 *
 * Custom property | Description | Default
 * ----------------|-------------|----------
 * `--progress-height` | Height of the progress indicator | `3px`
 * `--progress-color`  | Color of the progress indicator  |  `#0040a8`
 */
declare class CubaProgressIndicator extends Polymer.Element {
  readonly _loadingCounter: number|null|undefined;
  connectedCallback(): void;
  disconnectedCallback(): void;
  _incrementCounter(): void;
  _decrementCounter(): void;
  _counterChanged(counter: any): void;
}

interface HTMLElementTagNameMap {
  "cuba-progress-indicator": CubaProgressIndicator;
}
