/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   cuba-entity-list-view-behavior.html
 */

interface CubaEntityListViewBehavior {
  active: boolean|null|undefined;
  entities: any[]|null|undefined;
  entitiesCount: number|null|undefined;
  readonly moreDataAvailable: boolean|null|undefined;
  dataLoading: boolean|null|undefined;
  selectedEntity: object|null|undefined;
  reload(): any;
  remove(entity: any): void;
  _loadMore(): void;
  _computeMoreDataAvailable(entities: any, entitiesCount: any): any;
  _handleItemTap(event: any): void;
  _handleSelectionChange(event: any): void;
}

declare const CubaEntityListViewBehavior: object;
